stages:
  - stage: Build
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: Build
        steps:
          - task: DockerCompose@0
            displayName: Build
            inputs:
              containerregistrytype: "Container Registry"
              dockerRegistryEndpoint: "docker-hub"
              dockerComposeFile: "server/ci/docker/docker-compose.build.yml"
              action: "Run a Docker Compose command"
              dockerComposeCommand: up
  - stage: Test
    dependsOn: Build
    pool:
      vmImage: "ubuntu-latest"
    jobs:
      - job: UnitTests
        steps:
          - task: DockerCompose@0
            displayName: Run Tests
            inputs:
              containerregistrytype: "Container Registry"
              dockerRegistryEndpoint: "docker-hub"
              dockerComposeFile: "server/ci/docker/docker-compose.unittests.yml"
              action: "Run a Docker Compose command"
              dockerComposeCommand: up --build --abort-on-container-exit
          - task: CmdLine@2
            displayName: Copy test results
            inputs:
              script: docker cp wordki-server.ci.unittests:/server/tests/Cards.Domain.Tests/TestResults $(System.DefaultWorkingDirectory)/test
          - task: PublishTestResults@2
            displayName: Publish test results
            inputs:
              testResultsFormat: "JUnit"
              searchFolder: $(System.DefaultWorkingDirectory)/test
              testResultsFiles: "*.xml"
