CREATE SCHEMA IF NOT EXISTS cards;

CREATE TABLE cards."Owners" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_Owners" PRIMARY KEY ("Id")
);

CREATE TABLE cards."Sides" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Label" text NULL,
    "Example" text NULL,
    CONSTRAINT "PK_Sides" PRIMARY KEY ("Id")
);

CREATE TABLE cards."Groups" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ParentId" bigint NULL,
    "Front" text NOT NULL,
    "Back" text NOT NULL,
    "OwnerId" bigint NULL,
    CONSTRAINT "PK_Groups" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Groups_Owners_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES cards."Owners" ("Id")
);

CREATE TABLE cards."Cards" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FrontId" bigint NULL,
    "BackId" bigint NULL,
    "GroupId" bigint NULL,
    CONSTRAINT "PK_Cards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Cards_Groups_GroupId" FOREIGN KEY ("GroupId") REFERENCES cards."Groups" ("Id"),
    CONSTRAINT "FK_Cards_Sides_BackId" FOREIGN KEY ("BackId") REFERENCES cards."Sides" ("Id"),
    CONSTRAINT "FK_Cards_Sides_FrontId" FOREIGN KEY ("FrontId") REFERENCES cards."Sides" ("Id")
);

CREATE TABLE cards."Details" (
    "SideType" integer NOT NULL,
    "CardId" bigint NOT NULL,
    "Drawer" SMALLINT NOT NULL,
    "Counter" SMALLINT NOT NULL,
    "IsQuestion" boolean NOT NULL,
    "IsTicked" boolean NOT NULL,
    "NextRepeat" timestamp without time zone NULL,
    CONSTRAINT "PK_Details" PRIMARY KEY ("CardId", "SideType"),
    CONSTRAINT "FK_Details_Cards_CardId" FOREIGN KEY ("CardId") REFERENCES cards."Cards" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Cards_BackId" ON cards."Cards" ("BackId");

CREATE INDEX "IX_Cards_FrontId" ON cards."Cards" ("FrontId");

CREATE INDEX "IX_Cards_GroupId" ON cards."Cards" ("GroupId");

CREATE INDEX "IX_Cards_Id" ON cards."Cards" ("Id");

CREATE INDEX "IX_Details_CardId_SideType" ON cards."Details" ("CardId", "SideType");

CREATE INDEX "IX_Groups_Id" ON cards."Groups" ("Id");

CREATE INDEX "IX_Groups_OwnerId" ON cards."Groups" ("OwnerId");

CREATE INDEX "IX_Owners_Id" ON cards."Owners" ("Id");

CREATE INDEX "IX_Sides_Id" ON cards."Sides" ("Id");


