CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE users."Users" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Password" text NOT NULL,
    "Email" text NULL,
    "FirstName" text NULL,
    "Surname" text NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    "Status" integer NOT NULL,
    "ConfirmationDate" timestamp without time zone NOT NULL,
    "LoginDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE users."Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Type" integer NOT NULL,
    "UserId" uuid NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Roles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES users."Users" ("Id")
);

CREATE INDEX "IX_Roles_UserId" ON users."Roles" ("UserId");