// @host = http://localhost:5000
@host = http://147.135.208.14:5000

### logining user
# @name login
PUT {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
    "userName": "kamil",
    "password": "pass"
}

#
@authToken = Bearer {{login.response.body.$.response.token}}
@userId = {{login.response.body.$.response.id}}

### add group
POST {{host}}/groups/add HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "userId": "{{userId}}",
    "groupName":"prof - kierunek i ruch",
    "front":2,
    "back":1,
    "cards":[     
    ]
}

### get groups by userId
# @name allGroups
GET {{host}}/groups/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

#
@groupId = {{allGroups.response.body.$.groups[1].id}}


### get group by userId and groupId
# @name group
GET {{host}}/groups/{{userId}}/{{groupId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

#
@cardId = {{group.response.body.$.cards[0].id}}


### add cards from file

POST {{host}}/cards/add/file HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "userId": "{{userId}}",
    "groupId": "5",
    "itemSeparator":"|",
    "elementSeparator":"=",
    "itemsOrder":["FV","BV"],
    "content":""

}
