// @host = http://localhost:5000
@host = http://147.135.208.14:5000

### logining user
# @name login
PUT {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
    "userName": "kamil",
    "password": "pass"
}

#
@authToken = Bearer {{login.response.body.$.response.token}}
@userId = {{login.response.body.$.response.id}}

### add group
POST {{host}}/groups/add HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "userId": "{{userId}}",
    "groupName":"prof - żywność i kuchnia",
    "front":1,
    "back":2,
    "cards":[     
    ]
}

### get groups by userId
# @name allGroups
GET {{host}}/groups/{{userId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

#
@groupId = {{allGroups.response.body.$.groups[0].id}}


### get group by userId and groupId
# @name group
GET {{host}}/groups/{{userId}}/{{groupId}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

#
@cardId = {{group.response.body.$.cards[0].id}}


### add cards from file

POST {{host}}/cards/add/file HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "userId": "{{userId}}",
    "groupId": "{{groupId}}",
    "itemSeparator":"|",
    "elementSeparator":"=",
    "itemsOrder":["FV","BV"],
    "content":"
    abattoir=rzeźnia|
acrid=cierpki|
additive=substancja dodawana do jedzenia (wzmacniająca np. smak, kolor)|
ample=obszerny, obfity (np. obiad)|
appetiser=przystawka|
apricot=morela|
apron=fartuch kuchenny|
asparagus=szparagi|
aubergine=bakłażan|
bagel=bajgiel|
baking bowl=forma do pieczenia|
baking powder=proszek do pieczenia|
baking soda=soda oczyszczona|
baking tin=blacha do pieczenia|
banquet=bankiet|
bar=batonik|
barmaid=barmanka|
bartender=barman|
basil=bazylia|
battery hen=kurczak z chowu bateryjnego|
beetroot=burak|
bittersweet=słodko-gorzki|
bland=nijaki|
blender=mikser (kuchenny)|
bottle opener=otwieracz do butelek|
bowl=miska|
braise=udusić (mięso)|
braised beef=duszona wołowina|
bread board=deska do krojenia chleba|
breadcrumbs=bułka tarta|
brew=parzyć (herbatę)|
brew=warzyć (piwo)|
broccoli=brokuły|
broccoli=brokuł|
broth=rosół|
bun=bułka, bułeczka (słodka)|
buttermilk=maślanka|
candy floss=wata cukrowa|
canteen=stołówka (np. szkolna)|
carbonated drinks=napoje gazowane|
carp=karp|
cater=zaopatrzyć w żywność|
catering=katering|
caviar=kawior|
cereal=zboże|
chef=szef kuchni|
chew=żuć|
chicory=cykoria|
chip=kawałeczek|
chives=szczypiorek|
chop=siekać, ciąć|
chop=kotlet|
chopped=siekany|
chunk=kawał (np. sera)|
cinnamon=cynamon|
clove=ząbek (czosnku), goździk (przyprawa)|
coconut=orzech kokosowy|
cod=dorsz|
coffee grinder=młynek do kawy|
coffee pot=dzbanek do kawy|
cold dishes=dania na zimno|
cold drinks=napoje zimne|
cone=rożek (np. lody w rożku)|
confectionery=słodycze|
cookbook=książka kucharska|
cookery book=książka kucharska|
cool box=lodówka turystyczna|
corkscrew=korkociąg|
cornflour=mąka kukurydziana|
cottage cheese=twaróg|
cotton candy=wata cukrowa|
courgette=cukinia|
cranberry=żurawina|
crayfish=rak|
cream cake=tort|
crisp=chrupiący, kruchy|
crockery=porcelana stołowa|
croquet=krokiet|
cruet set=zestaw przypraw|
crumb=okruch, okruszek|
crunch=chrupać, wydawać chrupiący dźwięk|
crunchy=chrupiący, chrupki|
cuisine=kuchnia (np. polska)|
cumin=kminek|
curds=zsiadłe mleko|
cutlery=sztućce|
dairy products=przetwory mleczne|
decaffeinated=bezkofeinowa|
decanter=karafka|
dessert fork=widelec do deserów|
detestable=wstrętny, obrzydliwy|
dice=kroić w kostkę|
digest=trawić|
digestion=trawienie|
dine=jeść obiad|
dish of the day=danie dnia|
dish up=podawać potrawę do stołu|
dishcloth=ścierka do naczyń|
dishtowel=ścierka do naczyń|
dishwasher=zmywarka do naczyń|
dissolve=rozpuścić, rozwiązać|
distil=destylować, czerpać|
done=ugotowany, usmażony, skończony|
dough=ciasto (masa)|
drain=odsączyć|
drainer=suszarka do naczyń|
draught=łyk, haust (np. piwa)|
dressing=sos do sałatek|
drive-in restaurant=restauracja dla zmotoryzowanych|
dry=wytrawne|
dry wine=wino wytrawne|
eatery=restauracja, jadalnia|
edible=jadalny|
eel=węgorz|
egg beater=ubijaczka do jaj|
eggplant=bakłażan|
electric kettle=czajnik elektryczny|
fattening=tuczące|
fatty=tłusty, tłuszczowy|
fig=figa|
filling=nadzienie (np. ciasta)|
first course=pierwsze danie|
fish finger=paluszek rybny|
fizzy drink=gazowany napój|
flask=płaska butelka|
flavour=zapach, smak|
flesh=mięso, miąższ (owoców)|
flounder=flądra|
four-course meal=posiłek czterodaniowy|
French fries=frytki|
fried sausages=smażone kiełbaski|
funnel=lejek|
garnish=przybrać (np. jedzenie)|
gherkin=korniszon|
ginger=imbir|
gingerbread=piernik|
glutton=żarłok|
gooseberry=agrest|
gorge=napychać się|
gourmet=wyśmienity,smakowity (o jedzeniu, restauracji)|
grate=trzeć na tarce|
grated=utarty|
grater=tarka|
gravy=sos mięsny|
green pea=groszek|
grill=grilować|
grilled lamb=jagnięcina z rusztu|
grind=mielić|
grinder=młynek|
grounds=fusy, zmielona kawa|
gut=patroszyć|
hazelnut=orzech laskowy|
heater=grzałka, piecyk|
helping=porcja|
herring=śledź|
horseradish=chrzan|
hot dishes=dania na gorąco|
hot drinks=napoje gorące|
hotel in the city centre=hotel w centrum miasta|
icing=lukier|
icing sugar=cukier puder|
impure=nieczysty|
inedible=niejadalne|
instant=rozpuszczalny (np. kawa)|
juice extractor=sokowirówka|
knead=wyrobić ciasto|
kohlrabi=kalarepa|
ladle=chochla|
lamb=jagnięcina|
lard=smalec|
lean=chudy (mięso, rok)|
leek=por (roślina)|
lentil=soczewica|
lichi=liczi|
lick=lizać|
lid=pokrywka|
liquid=płyn, ciecz|
loaf=bochenek|
lobster=homar|
lollipop=lizak|
long drink=alkohol niskoprocentowy|
lump=grudka|
macaroni cheese=makaron z serem|
maize=kukurydza|
marjoram=majeranek|
marrow=kabaczek|
mashed=tłuczony, ubity|
mayonnaise=majonez|
meat grinder=maszynka do mielenia mięsa|
meat pastry=pasztet mięsny|
meatball=klopsik|
medium=średnio wysmażony|
medium wine=wino półsłodkie|
melt=roztopić|
millet=proso|
mince=posiekać, rozdrobnić|
minced meat=mięso mielone|
mouldy=spleśniały|
mussel=małż|
mutton=baranina|
nectarine=nektarynka|
nibble=skubać (np. chleb)|
noodles=kluski, makaron|
nutrition=odżywianie|
nutritious=pożywny|
oatmeal=mąka owsiana|
oregano=oregano|
ox tongue=ozór|
pan=rondel, misa|
pancake=naleśnik|
pantry=spiżarnia|
parsley=pietruszka|
pastry=ciasto (surowe)|
peanuts=orzeszki ziemne|
peel=obierać; łuszczyć się|
pepper pot=pieprzniczka|
pickle=marynować|
pickle=marynata|
pickled=kiszony|
pike=szczupak|
pint=pół kwarty, kufel (np. piwa)|
place setting=nakrycie (na stole)|
platter=półmisek|
poach=gotować (bez skorupki)|
Polish cuisine=kuchnia polska|
pomegranate=granat|
pork=wieprzowina|
porridge=owsianka|
quarter=ćwiartować|
radish=rzodkiewka|
raisin=rodzynek|
rare=krwisty|
raspberry=malina|
ravenous=wygłodniały|
raw=surowy (nieugotowany)|
raw meat=surowe mięso|
recipe=przepis kucharski|
refreshing drink=napój orzeźwiający|
refreshments=zakąski i napoje|
ribs=żeberka|
rice and beans=ryż z fasolką|
rinse=płukać|
ripe=dojrzały (np. owoc)|
roast beef=pieczeń wołowa|
roast lamb=pieczeń jagnięca|
roast mutton=pieczeń barania|
roast pork=pieczeń wieprzowa|
roast veal=pieczeń cielęca|
roasted pork=pieczona wieprzowina|
rolling pin=wałek do ciasta|
rum=rum|
sage=szałwia|
salmon=łosoś|
salt cellar=solniczka|
salt-free=nie zawierający soli|
saucepan=rondel|
saucer=spodek|
sausages and mash=kiełbaski z ziemniakami puree|
sauted chicken=duszony kurczak|
savory=cząber|
savoury=pikantny|
scramble=robić jajecznicę, rozbijać jaja|
scrambled egg=jajecznica|
scrambled eggs=jajecznica|
second helping=dokładka|
seethe=kipieć (woda); kotłować się, kłębić się|
shell=skorupka (jajka), łupina|
shell=łuskać|
shortcrust pastry=kruche ciasto|
shred=szatkować|
shrimp=krewetka|
sickly=mdły|
side dish=dodatek do dania (np. sałatka)|
side plate=talerzyk|
sieve=przesiać przez sito|
sieve=sito|
simmer=gotować na wolnym ogniu|
sink=zlew|
sip=łyczek|
sip=sączyć, popijać|
skimmed milk=chude mleko|
skin=zdzierać skórę, obdzierać ze skóry|
slice=kroić w plasterki|
slimming=odchudzający, wyszczuplający|
slurp=siorbać|
smash=zgnieść, rozbić|
smoked=wędzone (np. mięso)|
smoked fish=ryba wędzona|
smoked salmon=wędzony łosoś|
snack=podjadać|
snacks=zakąski, przekąski|
soft drinks=napoje bezalkoholowe|
solid=stały (nie płynny)|
sparkling mineral water=woda mineralna gazowana|
spice=przyprawiać|
spices=przyprawy|
spongy=gąbczasty, pulchny (ciasto)|
spoonful=łyżka stołowa (objętość)|
squash=kabaczek|
squid=kalmar|
stale=czerstwy|
staple=podstawowe, główne (o jedzeniu)|
starch=skrobia; krochmal|
starchy=skrobiowy|
starve=głodować|
starving=głodujący|
steak=stek|
steam=gotować na parze|
steamed fish=ryba gotowana na parze|
stew=dusić (np. warzywa)|
still=niegazowany (o wodzie)|
stir=mieszać|
stodgy=ciężki (o jedzeniu)|
stool=taboret|
strain=odcedzać (np. ziemniaki)|
straw=słomka|
strong drink=alkohol wysokoprocentowy|
stuffed=faszerowany|
stuffing=nadzienie|
sugar=słodzić|
sugar bowl=cukierniczka|
sweet wine=wino słodkie|
tablecloth=obrus|
tablespoon=łyżka stołowa|
takeaway=na wynos (np. jedzenie)|
takeaway food=jedzenie na wynos|
tangerine=mandarynka|
tarragon=estragon|
taste of=mieć smak (czegoś)|
tea=podwieczorek|
tender=delikatny|
thick=gęsty (np. sos)|
tin=puszka, konserwa|
tin opener=otwieracz do konserw|
tissue=serwetka, bibułka, chusteczka|
to have hiccups=mieć czkawkę|
toothpick=wykałaczka|
tray=taca|
tripe=flaki|
turkey=indyk|
turmeric=kurkuma|
turnip=rzepa|
unpalatable=niesmaczny, trudny do przełknięcia|
vat=kadź|
veal=cielęcina|
vegetarian=wegetariański|
vending machine=automat do sprzedaży (np. napojów, jedzenia)|
venison=dziczyzna|
vessel=naczynie|
vinegar=ocet|
walnut=orzech włoski|
whip=ubijać (np. pianę)|
whipped cream=bita śmietana|
whisk=trzepać (jajka)|
yeast=drożdże|
zucchini=cukinia"

}
