@host = http://localhost:5000

### logining user
# @name login
PUT {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
    "userName": "user_name",
    "password": "pass"
}

#
@authToken = Bearer {{login.response.body.$.response.token}}
@userId = {{login.response.body.$.response.id}}

### get repeats by userId
# @name repeats
GET {{host}}/cards/repeats/2 HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}