@host = http://localhost:5000

### logining user
# @name login
PUT {{host}}/users/login HTTP/1.1
Content-Type: application/json

{
    "userName": "userName",
    "password": "pass"
}

#
@authToken = Bearer {{login.response.body.$.token}}

### get repeats by userId
# @name repeats
GET {{host}}/repeats?GroupId=1&Count=1&LessonIncluded=true&Languages=test HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}
