@id = 4663083a-ead9-44dd-acf4-11810aaa78da

//@host = http://147.135.208.14:5000/users
@host = https://wordki-server.herokuapp.com/users

### registering user
# @name register
POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "name": "magda",
    "password": "pass",
    "email": "user@mail.com",
    "firstName": null,
    "surname": null
}

@id = {{register.response.body.$.response}}

### confirming user
PUT {{host}}/confirm HTTP/1.1
Content-Type: application/json

{
    "id": "{{id}}"
}

### logining user
# @name login   
PUT {{host}}/login HTTP/1.1
Content-Type: application/json

{
    "userName": "kamil",
    "password": "pass"
}

###

@authToken = Bearer {{login.response.body.$.response.token}}

### logining user
DELETE {{host}}/delete HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

{
    "id": "{{id}}"
}

### getUsers
GET {{host}} HTTP/1.1
Content-Type: application/json
Authorization: {{authToken}}

