version: "3.5"
services:
  wordki-client.ci.build:
    container_name: wordki-client.ci.build
    image: wordki-client/ci/build:${BUILD_BUILDID}
    build:
      context: ../../
      dockerfile: ./ci/docker/Dockerfile
      target: build
