version: "3.5"
services:
  wordki-client.ci.release:
    container_name: wordki-client.ci.release
    image: kamilsoloducha/wordki-client:${BUILD_BUILDID}
    build:
      context: ../../
      dockerfile: ./ci/docker/Dockerfile
      target: release
