version: "3.5"
services:
  wordki-server.ci:
    container_name: wordki-server.ci
    image: kamilsoloducha/wordki-server:latest
    build:
      context: ../../
      dockerfile: ./ci/docker/Dockerfile
      target: local
    ports:
      - 5000:5000
    env_file:
      - secrects.Development.env