version: "3.5"
services:
  wordki-server.ci.unittests:
    container_name: wordki-server.ci.unittests.${BUILD_BUILDID}
    image: kamilsoloducha/wordki-server:${BUILD_BUILDID}
    build:
      context: ../../
      dockerfile: ./ci/docker/Dockerfile
      target: tests
    command: dotnet test --test-adapter-path:. --logger:"junit"
