version: "3.5"
services:
  wordki-server:
    container_name: wordki-server
    image: kamilsoloducha/wordki-server:latest
    env_file:
      - secrets.Production.env
    ports:
      - 5000:5000
    network_mode: host
    volumes:
      - /home/pi/Documents/cert:/app/cert
