version: "3.5"
services:
  wordki-server.ci.build:
    container_name: wordki-server.ci.build.${BUILD_BUILDID}
    image: kamilsoloducha/wordki-server:${BUILD_BUILDID}
    build:
      context: ../../
      dockerfile: ./ci/docker/Dockerfile
      target: build
